kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: fraudguard
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 8080
        protocol: TCP
      - containerPort: 443
        hostPort: 8443
        protocol: TCP
      - containerPort: 30000   # Grafana NodePort
        hostPort: 3000
        protocol: TCP
      - containerPort: 30001   # Prometheus NodePort
        hostPort: 9090
        protocol: TCP
      - containerPort: 30002   # MLflow NodePort
        hostPort: 5001
        protocol: TCP
      - containerPort: 30003   # FraudGuard serve NodePort
        hostPort: 8001
        protocol: TCP
  - role: worker
  - role: worker
