FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir xgboost scikit-learn mlflow pandas numpy imbalanced-learn dvc dvc-gs google-cloud-storage

COPY src/train/ ./src/train/
COPY data/ ./data/

ENV MLFLOW_TRACKING_URI=http://mlflow:5000

ENTRYPOINT ["python", "src/train/train.py"]
