apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fraudguard-app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thorathharish/mlops-fraud-detection-platform
    targetRevision: main
    path: k8s/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
